# Generated by Django 4.2.3 on 2023-07-24 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('roll_number_booker', models.IntegerField(primary_key=True, serialize=False)),
                ('name_of_booker', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('hall_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('mobile_of_student', models.IntegerField(default=' ')),
                ('address_of_student', models.CharField(default=' ', max_length=20)),
                ('mobile_of_guest', models.IntegerField(default=0)),
                ('number_of_guests', models.IntegerField(default=0)),
                ('referred_booking', models.BooleanField(default=False)),
                ('roll_number_external_student', models.IntegerField(blank=True, null=True)),
                ('name_external_student', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_booking.room')),
            ],
        ),
    ]
