# Generated by Django 4.2.3 on 2023-07-25 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guest_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='hall_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
