# Generated by Django 4.1.2 on 2023-02-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
