# Generated by Django 4.1.2 on 2023-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='address_of_student',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=' '),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mobile_of_resident',
            field=models.IntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mobile_of_student',
            field=models.IntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(default=' '),
        ),
    ]
