# Generated by Django 4.1.2 on 2023-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='roll_number_booker',
            field=models.IntegerField(default=None),
        ),
    ]
