# Generated by Django 4.1.2 on 2023-02-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_booking', '0002_alter_reservation_address_of_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='mobile_of_resident',
            new_name='mobile_of_guest',
        ),
    ]
