# Generated by Django 4.2.3 on 2023-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_booking', '0003_delete_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
