# Generated by Django 4.1.2 on 2023-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_booking', '0004_alter_reservation_mobile_of_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name_referred_student',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='roll_number_booker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='roll_number_referred_student',
            field=models.IntegerField(null=True),
        ),
    ]
