# Generated by Django 4.1.2 on 2023-03-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_heading',
            field=models.TextField(null=True),
        ),
    ]
