# Generated by Django 4.2.3 on 2023-07-23 21:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('response', models.TextField()),
                ('id_map', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('query', models.TextField(null=True)),
                ('query_topic', models.CharField(default='Others', max_length=50)),
                ('query_heading', models.CharField(default='Query', max_length=150)),
                ('date', models.DateField(default=datetime.date.today)),
                ('upvote_number', models.IntegerField(default=0)),
                ('downvote_number', models.IntegerField(default=0)),
                ('votes', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
