# Generated by Django 4.1.2 on 2023-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_topic',
            field=models.CharField(default='Others', max_length=50),
        ),
    ]
