# Generated by Django 4.2.3 on 2023-08-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='email',
        ),
        migrations.RemoveField(
            model_name='queryresponse',
            name='email',
        ),
    ]
