# Generated by Django 4.1.2 on 2023-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_query_query_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_heading',
            field=models.CharField(default='Query', max_length=150),
        ),
    ]
