# Generated by Django 4.1.2 on 2023-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_query_query_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='downvote_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='query',
            name='upvote_number',
            field=models.IntegerField(default=0),
        ),
    ]
