# Generated by Django 4.1.2 on 2023-03-01 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('query', '0004_query_downvote_number_query_upvote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='votes',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
