# Generated by Django 4.1.2 on 2023-03-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
