# Generated by Django 4.2.3 on 2023-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras_name', models.CharField(max_length=35, null=True)),
                ('extras_price', models.IntegerField(null=True)),
                ('extras_type', models.CharField(max_length=10, null=True)),
                ('extras_day', models.CharField(max_length=10, null=True)),
                ('extras_quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_item_name', models.CharField(max_length=35, null=True)),
                ('day_of_the_week', models.CharField(max_length=10, null=True)),
                ('type_of_meal', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtrasOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('order_date', models.DateField(null=True)),
                ('order_month', models.IntegerField(null=True)),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('item_map', models.ManyToManyField(to='mess_site.messextras')),
            ],
        ),
    ]
