# Generated by Django 4.1.2 on 2023-01-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0013_rename_item_id_extrasorder_item_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasorder',
            name='order_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
