# Generated by Django 4.1.2 on 2023-01-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0014_extrasorder_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messextras',
            name='extras_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
