# Generated by Django 4.1.2 on 2023-01-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0015_messextras_extras_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messextras',
            name='extras_day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='messextras',
            name='extras_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
