# Generated by Django 4.1.2 on 2023-03-05 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_poll_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='poll_downotes',
            new_name='opt1_votes',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='poll_upvotes',
            new_name='opt2_votes',
        ),
        migrations.RenameField(
            model_name='pollvotes',
            old_name='downvote',
            new_name='opt1',
        ),
        migrations.RenameField(
            model_name='pollvotes',
            old_name='upvote',
            new_name='opt2',
        ),
        migrations.AddField(
            model_name='poll',
            name='opt1',
            field=models.CharField(default='Yes', max_length=300),
        ),
        migrations.AddField(
            model_name='poll',
            name='opt2',
            field=models.CharField(default='No', max_length=300),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_created',
            field=models.DateField(default=datetime.date(2023, 3, 6)),
        ),
    ]
