# Generated by Django 4.1.2 on 2023-03-07 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_poll_downotes_poll_opt1_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_created',
            field=models.DateField(default=datetime.date(2023, 3, 7)),
        ),
    ]
