# Generated by Django 4.1.2 on 2023-03-08 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_poll_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_created',
            field=models.DateField(default=datetime.date(2023, 3, 9)),
        ),
    ]
