# Generated by Django 4.2.3 on 2023-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0002_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
