# Generated by Django 4.2.3 on 2023-08-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0003_userprofile_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User_OTP',
        ),
    ]
