# Generated by Django 4.2.3 on 2023-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0004_alter_userprofile_is_staff_delete_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
