# Generated by Django 4.1.2 on 2023-02-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
