# Generated by Django 4.1.2 on 2023-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0006_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='designation',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
