# Generated by Django 4.1.2 on 2023-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0007_user_otp_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_otp',
            name='designation',
        ),
    ]
