# Generated by Django 4.1.2 on 2023-03-03 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(null=True)),
                ('query_topic', models.CharField(default='Others', max_length=50)),
                ('query_heading', models.CharField(default='Query', max_length=150)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
