# Generated by Django 4.1.2 on 2023-03-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_anonymouscomplaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
