# Generated by Django 4.1.2 on 2023-03-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_student_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='student_excel',
        ),
    ]
